#!/bin/bash

# will update the antenna heights from the rinex files.
# expects all stations to have the same antenna type, and that the height information is correct in the header of he 1st day, and constant for the campaign
# AVN Wed Jul 13 15:33:00 EDT 2011

ANTTYPE=ATR41249    # obtained from /home/gpslab/goa-var/sta_info/pcenter
NDAYS=30             # number of days to use this header starting from begin time
BYEAR=2011	     # beginning year, month, and day of campaign
BMO=08
BDAY=22


NSEC=`echo $NDAYS | awk '{printf "%012.2f", 86400.*$1}'`
for DIR in ???? 
 do
   FILE=`ls -1 $DIR/*o | head -1`
   awk '$4~"ANTENNA" {
    print " '$DIR' '$DIR' '$BYEAR' '$BMO' '$BDAY' 00:00:00.00 '$NSEC' '$ANTTYPE'        0.0000     0.0000     0.0000     "$1" l " }' $FILE
done
